alarm: Cpu_usage_above_80
on: system.cpu
class: Utilization
type: System
component: CPU
host labels: _os=linux

lookup: average -3m of user,system,softirq,irq,guest,steal
units: %
every: 1m

warn: $this > 70
crit: $this > 85

summary: System CPU utilization
info: Average CPU utilization over the last 10 minutes
